name = "aiken-lang/finite-distribution"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/finite-distribution'"

[repository]
user = "aiken-lang"
project = "finite-distribution"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
